### ISSUE TITLE
Version display

### ISSUE THREAD

**Issue by GV3** [Backendless/ActionScriptSDK#2]
Could you display on the README what version of BACKENDLESS is supported by the SDK?

I suppose it's at the latest, is this 3.0?

Thank you

**Comment by scadgek** [comment]
We don't break backward compatibility between any versions.
So the answer is - all versions are supported.

**Comment by GV3** [comment]
That you don't break backward compatibility does't really mean that you support the latest, it would be great to be able to read quickly in your README what version is the supported to know what if new features are supported, etc.. 

I don't see how not breaking backward compatibility means that future versions or ALL versions are supported.

If you release a new method today, and you don't break the backward compatibility... this does not mean that automagically the new method is supported in the ActionScriptSDK.

**Comment by markpiller** [comment]
SDK for ActionScript is not actively maintained by Backendless Corp. The SDK is open source and the community is welcome to contribute.
